<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\BLAZOR_WASM_CLEAN_ARQUITECTURE.Shared\BLAZOR_WASM_CLEAN_ARQUITECTURE.Shared.csproj" />
  </ItemGroup>

</Project>
